import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { buildInstallExpression, buildRemoveExpression, buildStatusExpression } from "../scripts/lib/renderer.mjs";

test("builds self-contained idempotent renderer expressions", () => {
  const expression = buildInstallExpression({ css: "#root{}", themes: [{ id: "one" }], activeId: "one" });
  assert.doesNotThrow(() => new Function(`return ${expression}`));
  assert.match(expression, /MutationObserver/);
  assert.match(expression, /data-vscode-theme-kind/);
  assert.match(expression, /ide night/);
  assert.match(expression, /prefers-color-scheme: dark/);
  assert.match(expression, /wbasNativeAppearance/);
  assert.match(expression, /appearanceObserver\.disconnect/);
  assert.match(expression, /Date\.now\(\) \+ 30_000/);
  assert.match(expression, /missing markers/);
  assert.match(expression, /attachShadow/);
  assert.match(expression, /analyzeImage/);
  assert.match(expression, /workbuddy-ambient-skin\.custom/);
  assert.match(expression, /custom-v2/);
  assert.match(expression, /editor-input/);
  assert.match(expression, /重命名保存失败/);
  assert.match(expression, /删除“/);
  assert.doesNotMatch(expression, /window\.prompt/);
  assert.doesNotMatch(expression, /window\.confirm/);
  assert.match(expression, /wbasMaterial/);
  assert.match(expression, /--wbas-material-blur/);
  assert.match(expression, /immersiveFloor/);
  assert.match(expression, /theme\.modes\.homeOpacity \* \.94/);
  assert.match(expression, /text-overflow:ellipsis/);
  assert.match(expression, /button\.title = theme\.name/);
  assert.match(expression, /slice\(0, 8\)/);
  assert.match(expression, /candidate\.id === "paper-aurora"/);
  assert.match(expression, /选择本地图片/);
  assert.match(expression, /orb-position-v1/);
  assert.match(expression, /setPointerCapture/);
  assert.match(expression, /pointercancel/);
  assert.match(expression, /prefers-reduced-motion/);
  assert.match(expression, /cubic-bezier/);
  assert.match(expression, /data-dock/);
  assert.match(expression, /tuning-v1/);
  assert.match(expression, /调整氛围/);
  assert.match(expression, /恢复主题推荐值/);
  assert.match(expression, /--wbas-bg-brightness/);
  assert.match(expression, /--wbas-bg-saturation/);
  assert.match(expression, /boundedTuning/);
  assert.match(expression, /生成主题收藏卡/);
  assert.match(expression, /share-preview/);
  assert.match(expression, /renderShareCard/);
  assert.match(expression, /toBlob\(resolve, "image\/png"\)/);
  assert.match(expression, /YOUR WORKSPACE, YOUR ATMOSPHERE/);
  assert.match(expression, /不包含聊天内容/);
  assert.match(expression, /handleShareKey/);
  assert.match(expression, /analysis-v1/);
  assert.match(expression, /analysis-v2/);
  assert.match(expression, /analysis-v4/);
  assert.match(expression, /rgbToOklch/);
  assert.match(expression, /oklchToRgb/);
  assert.match(expression, /hueDistance/);
  assert.match(expression, /contrastRatio/);
  assert.match(expression, /algorithmVersion: 4/);
  assert.match(expression, /generatedPalettes/);
  assert.match(expression, /palettesForTheme/);
  assert.match(expression, /minimum, direction/);
  assert.match(expression, /图片已保存/);
  assert.match(buildRemoveExpression(), /cleanup\(\)/);
  assert.match(buildStatusExpression(), /installed/);
  assert.match(buildStatusExpression(), /nativeAppearance/);
});

test("keeps native dark-mode controls readable inside skin surfaces", async () => {
  const css = await readFile(new URL("../assets/ambient.css", import.meta.url), "utf8");
  assert.match(css, /--cb-input-button-foreground: color-mix\(in srgb, var\(--wbas-text\)/);
  assert.match(css, /--cb-button-primary-foreground: var\(--wbas-surface\)/);
  assert.match(css, /--cb-button-secondary-foreground: var\(--wbas-text\)/);
  assert.match(css, /--cb-icon-default: color-mix\(in srgb, var\(--wbas-text\)/);
  assert.match(css, /data-wbas-native-appearance="dark"/);
  assert.match(css, /data-wbas-native-appearance="light".*color-scheme: light/);
  assert.match(css, /--wbas-surface: var\(--wbas-dark-surface\)/);
  assert.match(css, /--wbas-text: var\(--wbas-dark-text\)/);
  assert.match(css, /--wbas-accent: var\(--wbas-dark-accent\)/);
  assert.match(css, /body\[data-application-name="workbuddy"\] \.sidebar-next/);
  assert.match(css, /body\[data-application-name="workbuddy"\] \[class\*="input-area-container"\]/);
});
